name: senter
description: "Aplikasi lampu senter sederhana dengan konsep pisang untuk menyalakan flash kamera sebagai sumber cahaya."
publish_to: 'none'
version: 0.1.0

authors:
  - Dian Mukti Wibowo <onyetcorp@gmail.com>

homepage: https://onyet.id

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  torch_control: ^0.4.1
  google_mobile_ads: ^5.0.0
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  fonts:
    - family: OpenMoji
      fonts:
        - asset: assets/fonts/OpenMoji-Black.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/light_bulb.png"

flutter_native_splash:
  color: "#FFD700"  # Yellow banana color
  image: assets/icons/light_bulb.png
  android: true
  ios: true
